# -*- coding: utf-8 -*-
"""Fast ResNet50 Model for Brain Tumor Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14i43YRuxgJEUvgP7aRSfxftaBvzONSrC
"""

# =====================================
# ⚡️ Fast ResNet50 Model for Brain Tumor Detection
# =====================================

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import os
from zipfile import ZipFile

# Enable faster GPU computations (optional but recommended)
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy('mixed_float16')

# Step 1: Extract dataset
zip_path = '/content/archive (8).zip'
extract_path = '/content/brain_tumor_resnet_fast'

with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Dataset extracted successfully at:", extract_path)

# Step 2: Prepare data
img_size = (150, 150)   # smaller = faster
batch_size = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = datagen.flow_from_directory(
    extract_path,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    extract_path,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='validation'
)

# Step 3: Build ResNet50 Model (frozen base)
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(150,150,3))
base_model.trainable = False

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(1, activation='sigmoid', dtype='float32')  # ensure correct output type
])

model.compile(optimizer=Adam(learning_rate=1e-4),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Step 4: Train model with fewer steps
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5,          # train only 5 epochs first to save time
    steps_per_epoch=50,   # limit steps per epoch for speed
    validation_steps=10,  # small validation sample
    verbose=1
)

# Step 5: Save model
model.save('/content/brain_tumor_resnet50_fast.h5')
print("✅ Model saved as brain_tumor_resnet50_fast.h5")

# Step 6: Plot accuracy and loss
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy')
plt.legend()
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss')
plt.legend()
plt.show()

# Step 7: Quick evaluation (optional full test later)
val_generator.reset()
y_pred = model.predict(val_generator, verbose=0)
y_pred = (y_pred > 0.5).astype(int).ravel()

y_true = val_generator.classes
cm = confusion_matrix(y_true, y_pred)
labels = list(val_generator.class_indices.keys())

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print(classification_report(y_true, y_pred, target_names=labels))